server:
    port: 7081
spring:
  application:
    name: doctor-portal
  sleuth:
    sampler:
      # Default value is 10
      #  % of los tht weill be exporTED TO zipkin
      rate: 100

  # Can be ignored if default values are used 
  zipkin:
    # Default Stats
    enabled: false
    # Defult Zipkin URL
    base-url: http://localhost:9411